language: ruby
cache: bundler
notifications:
  email: false
  slack:
    secure: rUAOGovjFdur1TjCcm7+c2Chl4EKaR47W4FhgWVC+BE7Hgr/QEbXr6IVxXiOmLqidPvp/58mkLM/QN8z7YPv/pqmX/E9KHm76ZtP6xvGrjxbihQcY/U1+j/rcyTg9x4VmQmvRhaiOjRzBLUhS2iQ+EZ6TW3PgxCiZO2e5Dwr/ZLW7QtM1E9rsJMY43g3Sl/qgEVF+E4rNRXmDln7pParDzZ04DUVIlzVBeUViIkmyBuVTlqbuKieWmjH1INKFMxsKqM7AAtyZMlshVNpXFOF8a9TTVLB6aU3c4r9zpIC6pNNZavmeews6dTCKdfcqiUy/GijJkzTkvRD7F9wMBdPuUrCTttaVxAgFnCLim+l2R5SuQZTAEcDlYe0TC2UhioELV8F8Yr5XSUQd3y36QHEr8hp+ruDa7TGrrEKmxQFyv51Gq+Ho2pxtg2fnKVsXfe73JOI+yZiSIe1Sr7e3tXnPLykaMfLid1X2XSiot2KteO+1iiYdOhMZ8MIJsjh9J+TeTMEadgi4Gga4gRFSZrPjbeq5hJQO2om8Z3exTdpufiKRuPGBmaP0ssorzc5xmQX+W4+/VQj5f7m709AkjrfWm/DAkc6S/b9DvWQHyz0R3n0wnAoe1cA4ZVDFIqixqcLlcQnmHKhXqCD8sOFY2zoswh+rP3LiNFPTNg/C7mnPMg=
rvm:
  - 2.3.1
before_script:
  - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  - bundle exec rails db:create --all
  - bundle exec rails db:migrate
script:
  - bundle exec rails ci:tests
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: o2yh4RG22qRN+gyiW17Wo45/ipmOCLR39odTVTmS/QnyALsCiIDN6tGfbd1YUS06+X6/w/dfMpAE/jqPr6o41lMZfxMinzinwaA548WjWiTLYQnCYp6GUAs6Un32ILQviMA7NhPEOX/jWJUSdquVaksceJlnXt9P6S5eb7A7BJkGWZ8be/gGdPLS4So/2tUhjDFx+ZYMbOPX9IJ64Uk1TMJy/fFx381me21jYpKwmeM8SR9F0qSKXZO8uBRBj3SOrPsb5ToyUjQ9SZiOpFyU+4tI/utJoseE3IMs3HKpRM853t+3rfFqStA9hzjbFT85duEH6mC+LajMPJBaFZABrcSPz3L6Av8WzOc62QRUq0k8USd89oB+WCm0UyDXl1Kx86ns21fB83T7XoW8gWGWZQgjKkOqINSnQkFsZ+h/Y1rzkpQE4PIDRJ9EzINRHzxVFUHgSMVGMGtx80RoxzKalwIlGetJ9gdtye9BWg8N3CqjBSjssbrVaeq2HU1AM4gk5PTIE+zwEC+4z+KvPpu1AT2V8SNaSFn2sllA/k+WVc6gBPaoe8VmbIw+x/ql3XslrkHXBg2yqI6Fbk5U/vkVdt3yZN+sc9pCAoKS6Or33uXFKsgj2OBB3qlHbwS+9mQmM/S+c1ku6S0GV5Xvkk0MjU0mxq+o6FtAjrw76q3T1G4=
  app:
    develop: homechefs
  on:
    repo: CraftAcademy/homechef
  run:
    - bundle exec rake db:migrate
